apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "mcp.opendatahub.io/v1alpha1",
          "kind": "MCPServer",
          "metadata": {
            "annotations": {
              "mcp.opendatahub.io/deploymentmode": "RawDeployment",
              "mcp.opendatahub.io/mcpservertemplate": "mcp-operator-mcpserver-template",
              "mcp.opendatahub.io/visibility": "hidden"
            },
            "labels": {
              "app.kubernetes.io/name": "mcp-operator"
            },
            "name": "mcp-workday"
          },
          "spec": {
            "container": {
              "image": "quay.io/vajain/mcp-workday:6.0",
              "name": "mcpserver-container"
            }
          }
        },
        {
          "apiVersion": "mcp.opendatahub.io/v1alpha1",
          "kind": "MCPServerTemplate",
          "metadata": {
            "annotations": {
              "openshift.io/display-name": "MCP Server Template"
            },
            "name": "mcp-operator-mcpserver-template",
            "namespace": "mcp-operator-system"
          },
          "spec": {
            "containers": [
              {
                "image": "$(mcp-server-image)",
                "imagePullPolicy": "IfNotPresent",
                "name": "mcpserver-container",
                "ports": [
                  {
                    "containerPort": 8080,
                    "protocol": "TCP"
                  }
                ],
                "resources": {
                  "limits": {
                    "cpu": "500m",
                    "memory": "512Mi"
                  },
                  "requests": {
                    "cpu": "250m",
                    "memory": "128Mi"
                  }
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File"
              }
            ]
          }
        },
        {
          "apiVersion": "mcp.opendatahub.io/v1alpha1",
          "kind": "MCPServerTemplate",
          "metadata": {
            "annotations": {
              "openshift.io/display-name": "MCP Server Template"
            },
            "name": "mcpserver-template"
          },
          "spec": {
            "containers": [
              {
                "image": "$(mcp-server-image)",
                "imagePullPolicy": "IfNotPresent",
                "name": "mcpserver-container",
                "ports": [
                  {
                    "containerPort": 8080,
                    "protocol": "TCP"
                  }
                ],
                "resources": {
                  "limits": {
                    "cpu": "500m",
                    "memory": "512Mi"
                  },
                  "requests": {
                    "cpu": "250m",
                    "memory": "128Mi"
                  }
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
    containerImage: quay.io/vajain/mcp-operator:8.0
    createdAt: "2025-05-28T07:46:29Z"
    description: MCP Operator for deployment and management of MCP Servers.
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    repository: https://github.com/btc-hackathon/mcp-operator
    tectonic-visibility: ocs
  name: mcp-operator.v0.0.7
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MCPServer is the Schema for the mcpservers API
      displayName: MCPServer
      kind: MCPServer
      name: mcpservers.mcp.opendatahub.io
      statusDescriptors:
      - description: Conditions store the status conditions of the MCPServer instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
    - description: MCPServerTemplate is the Schema for the mcpservertemplates API
      displayName: MCPServer Template
      kind: MCPServerTemplate
      name: mcpservertemplates.mcp.opendatahub.io
      statusDescriptors:
      - description: Conditions store the status conditions of the MCPServerTemplate
          instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: |-
    MCP Operator is designed for deployment of MCP Server application on Openshift env.

    * Create Deployment, Service & Route resource when deploy in RawDeployment mode.
    * Create Knative Service resource when deploy in Serverless mode.

    **IMPORTANT!** MCP Operator may need Serverless Operator be installed if running in Serverless mode.
  displayName: MCP Operator
  icon:
  - base64data: PHN2ZyBmaWxsPSJjdXJyZW50Q29sb3IiIGZpbGwtcnVsZT0iZXZlbm9kZCIgaGVpZ2h0PSIxZW0iIHN0eWxlPSJmbGV4Om5vbmU7bGluZS1oZWlnaHQ6MSIgdmlld0JveD0iMCAwIDI0IDI0IiB3aWR0aD0iMWVtIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjx0aXRsZT5Nb2RlbENvbnRleHRQcm90b2NvbDwvdGl0bGU+PHBhdGggZD0iTTE1LjY4OCAyLjM0M2EyLjU4OCAyLjU4OCAwIDAwLTMuNjEgMGwtOS42MjYgOS40NGEuODYzLjg2MyAwIDAxLTEuMjAzIDAgLjgyMy44MjMgMCAwMTAtMS4xOGw5LjYyNi05LjQ0YTQuMzEzIDQuMzEzIDAgMDE2LjAxNiAwIDQuMTE2IDQuMTE2IDAgMDExLjIwNCAzLjU0IDQuMyA0LjMgMCAwMTMuNjA5IDEuMThsLjA1LjA1YTQuMTE1IDQuMTE1IDAgMDEwIDUuOWwtOC43MDYgOC41MzdhLjI3NC4yNzQgMCAwMDAgLjM5M2wxLjc4OCAxLjc1NGEuODIzLjgyMyAwIDAxMCAxLjE4Ljg2My44NjMgMCAwMS0xLjIwMyAwbC0xLjc4OC0xLjc1M2ExLjkyIDEuOTIgMCAwMTAtMi43NTRsOC43MDYtOC41MzhhMi40NyAyLjQ3IDAgMDAwLTMuNTRsLS4wNS0uMDQ5YTIuNTg4IDIuNTg4IDAgMDAtMy42MDctLjAwM2wtNy4xNzIgNy4wMzQtLjAwMi4wMDItLjA5OC4wOTdhLjg2My44NjMgMCAwMS0xLjIwNCAwIC44MjMuODIzIDAgMDEwLTEuMThsNy4yNzMtNy4xMzNhMi40NyAyLjQ3IDAgMDAtLjAwMy0zLjUzN3oiPjwvcGF0aD48cGF0aCBkPSJNMTQuNDg1IDQuNzAzYS44MjMuODIzIDAgMDAwLTEuMTguODYzLjg2MyAwIDAwLTEuMjA0IDBsLTcuMTE5IDYuOTgyYTQuMTE1IDQuMTE1IDAgMDAwIDUuOSA0LjMxNCA0LjMxNCAwIDAwNi4wMTYgMGw3LjEyLTYuOTgyYS44MjMuODIzIDAgMDAwLTEuMTguODYzLjg2MyAwIDAwLTEuMjA0IDBsLTcuMTE5IDYuOTgyYTIuNTg4IDIuNTg4IDAgMDEtMy42MSAwIDIuNDcgMi40NyAwIDAxMC0zLjU0bDcuMTItNi45ODJ6Ij48L3BhdGg+PC9zdmc+
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - serving.knative.dev
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - maistra.io
          resources:
          - servicemeshcontrolplanes
          verbs:
          - get
          - list
          - use
          - watch
        - apiGroups:
          - maistra.io
          resources:
          - servicemeshmembers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - mcp.opendatahub.io
          resources:
          - mcpservers
          - mcpservertemplates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - mcp.opendatahub.io
          resources:
          - mcpservers/finalizers
          - mcpservertemplates/finalizers
          verbs:
          - update
        - apiGroups:
          - mcp.opendatahub.io
          resources:
          - mcpservers/status
          - mcpservertemplates/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - serving.knative.dev
          resources:
          - services/status
          verbs:
          - get
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: mcp-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: mcp-operator
          control-plane: controller-manager
        name: mcp-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/vajain/mcp-operator:12.0
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 1Gi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: mcp-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: mcp-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - MCP
  - Operator
  - RedHat
  - Openshift
  links:
  - name: Mcp Operator
    url: https://mcp-operator.domain
  maintainers:
  - email: vajain@redhat.com
    name: Vaibhav Jain
  maturity: alpha
  provider:
    name: Vaibhav Jain
    url: https://github.com/btc-hackathon/mcp-operator
  version: 0.0.7
