# permissions for end users to view mcpservertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpservertemplate-viewer-role
rules:
- apiGroups:
  - mcp.mcp.opendatahub.io
  resources:
  - mcpservertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mcp.mcp.opendatahub.io
  resources:
  - mcpservertemplates/status
  verbs:
  - get
