---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mcp.mcp.opendatahub.io
  resources:
  - mcpservers
  - mcpservertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcp.mcp.opendatahub.io
  resources:
  - mcpservers/finalizers
  - mcpservertemplates/finalizers
  verbs:
  - update
- apiGroups:
  - mcp.mcp.opendatahub.io
  resources:
  - mcpservers/status
  - mcpservertemplates/status
  verbs:
  - get
  - patch
  - update
