apiVersion: mcp.opendatahub.io/v1alpha1
kind: MCPServerTemplate
metadata:
  annotations:
    openshift.io/display-name: 'Default Model Server Template'
  labels:
    opendatahub.io/dashboard: 'true'
  name: mcpservertemplate-default
spec:
  containers:
    - name: mcpserver-container
      image: $(mcp-server-image)
      ports:
        - containerPort: 8080
          protocol: TCP