apiVersion: mcp.opendatahub.io/v1alpha1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-operator
    app.kubernetes.io/managed-by: kustomize
  annotations:
    mcp.opendatahub.io/deploymentmode: RawDeployment
    mcp.opendatahub.io/visibility: exposed
    mcp.opendatahub.io/mcpservertemplate: mcp-operator-mcpservertemplate-default
  name: mcpserver-sample
spec:
  container:
    name: mcpserver-container
    image: quay.io/vajain/mcp-workday:6.0