apiVersion: mcp.opendatahub.io/v1alpha1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-operator
  annotations:
    mcp.opendatahub.io/deploymentmode: RawDeployment
    mcp.opendatahub.io/visibility: hidden
    mcp.opendatahub.io/mcpservertemplate: mcp-operator-mcpserver-template
  name: mcp-workday
spec:
  container:
    name: mcpserver-container
    image: quay.io/vajain/mcp-workday:6.0